### ISSUE TITLE
Please provide your solution as well

### ISSUE THREAD

**Issue by khtan** [walkhard/linq-exercises#1]
Hi,
Thanks for a fun way to review Linq. For some tests, there is more than one way to do it. It would be interesting to compare solutions just to learn alternative ways of solving the same problem.

For example: First_n_greater_than_10_if_not_found_return 0
            int result = TestData.Numbers.Where(x => x>10).FirstOrDefault();
            int result = TestData.Numbers.FirstOrDefault(x => x > 10);

**Comment by zbma** [comment]
Hi @khtan 

Sorry for late repy.

Yes, some exercises can be solved in more ways. I don't want to give out solutions. The main point of exercises is to find solutions on your own, so you have to **practice** it instead of **read** it. Basically it's easier to learn/remember when you do this way.

I'm glad you liked it, I've decided to add some more exercises soon, be sure to check them out!

**Comment by benkoshy** [comment]
@walkhard am in complete agreement: it's best to practice rather than read.
